version: '4.21.1'

services:

  nginx:
    image: nginx:1.18.0-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/usr/src/static/
      - ./media:/usr/src/media/

  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - ./static:/app/meeting/static
      - ./media:/app/meeting/media
    expose:
      - 8000
    env_file:
      - ./.env

  redis:
    image: redis:7.0.11-alpine
    hostname: redis

  worker:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /app/docker/backend/worker-entrypoint.sh
    volumes:
      - ./static:/app/meeting/static
      - ./media:/app/meeting/media
    depends_on:
      - web
      - redis
    env_file:
      - ./.env











